-- MySQL Script generated by MySQL Workbench
-- 03/26/17 21:24:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema controlsales
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controlsales
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controlsales` DEFAULT CHARACTER SET utf8 ;
USE `controlsales` ;

-- -----------------------------------------------------
-- Table `controlsales`.`tipo_identificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`tipo_identificacion` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`tipo_identificacion` (
  `id_tipo_identificacion` INT NOT NULL AUTO_INCREMENT COMMENT 'llave primaria',
  `descripcion` VARCHAR(100) NOT NULL COMMENT 'nombre del tipo de identificacion',
  `sigla` VARCHAR(10) NOT NULL COMMENT 'sigla ejemploe: CC, NIT, CE, TI',
  `fecha_creacion` DATETIME NULL COMMENT 'datos de auditoria',
  `usuario_creacion` VARCHAR(50) NULL COMMENT 'datos de auditoria',
  PRIMARY KEY (`id_tipo_identificacion`),
  UNIQUE INDEX `sigla_UNIQUE` (`sigla` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`cliente` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT COMMENT 'llave primaria',
  `nombres` VARCHAR(200) NULL COMMENT 'nombres del cliente',
  `apellidos` VARCHAR(200) NULL COMMENT 'apellidos del cliente',
  `identificacion` BIGINT(15) NULL COMMENT 'número de identicicación del cliente',
  `id_tipo_identificacion` INT NULL COMMENT 'tipo de identificación, ejemplo: cedula, NIT, cedula de extranjeria',
  `email` VARCHAR(100) NULL COMMENT 'correo electronico',
  `telefono` VARCHAR(50) NULL COMMENT 'teléfono fijo o celular',
  `direccion` VARCHAR(200) NULL,
  `fecha_creacion` DATETIME NULL COMMENT 'datos de auditoria',
  `usuario_creacion` VARCHAR(50) NULL COMMENT 'datos de auditoria',
  `fecha_actualizacion` DATETIME NULL COMMENT 'datos de auditoria',
  `usuario_actualizacion` VARCHAR(50) NULL COMMENT 'datos de auditoria',
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `identificacion_UNIQUE` (`identificacion` ASC),
  INDEX `fk_cliente_tipo_id_idx` (`id_tipo_identificacion` ASC),
  CONSTRAINT `fk_cliente_tipo_id`
    FOREIGN KEY (`id_tipo_identificacion`)
    REFERENCES `controlsales`.`tipo_identificacion` (`id_tipo_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`parametro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`parametro` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`parametro` (
  `id_parametro` INT NOT NULL AUTO_INCREMENT COMMENT 'llave primaria',
  `grupo` VARCHAR(100) NULL COMMENT 'grupo de parámetros',
  `llave` VARCHAR(100) NULL COMMENT 'llave del parámetro',
  `valor_cadena` VARCHAR(100) NULL COMMENT 'valor en string',
  `valor_numero` INT NULL COMMENT 'valor numérico',
  `estado` VARCHAR(1) NULL COMMENT 'Activo=A, Inactivo=I',
  `fech_creacion` DATETIME NULL COMMENT 'datos de auditoria',
  `usuario_creacion` VARCHAR(50) NULL COMMENT 'datos de auditoria',
  PRIMARY KEY (`id_parametro`),
  UNIQUE INDEX `grupo_llave_UNIQUE` (`grupo` ASC, `llave` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`empresa` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`empresa` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `razonsocial` VARCHAR(200) NULL,
  `representante` VARCHAR(200) NULL,
  `identificacion` BIGINT(15) NULL,
  `id_tipo_identificacion` INT NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(200) NULL,
  `regimen` VARCHAR(50) NULL,
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(50) NULL,
  PRIMARY KEY (`idempresa`),
  INDEX `fk_empresa_tipo_id_idx` (`id_tipo_identificacion` ASC),
  CONSTRAINT `fk_empresa_tipo_id`
    FOREIGN KEY (`id_tipo_identificacion`)
    REFERENCES `controlsales`.`tipo_identificacion` (`id_tipo_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `razonsocial` VARCHAR(200) NULL,
  `representante` VARCHAR(200) NULL,
  `id_tipo_identificacion` INT NULL,
  `identificacion` BIGINT(15) NULL,
  `telefono` VARCHAR(100) NULL,
  `celular` VARCHAR(100) NULL,
  `direccion` VARCHAR(200) NULL,
  `email` VARCHAR(100) NULL,
  `estado` VARCHAR(1) NULL COMMENT 'Activo=A, Inactivo=I',
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(50) NULL,
  `fecha_actualizacion` DATETIME NULL,
  `usuario_actualizacion` VARCHAR(50) NULL,
  PRIMARY KEY (`id_proveedor`),
  UNIQUE INDEX `identificacion_UNIQUE` (`identificacion` ASC),
  INDEX `fk_proveedor_tipo_id_idx` (`id_tipo_identificacion` ASC),
  CONSTRAINT `fk_proveedor_tipo_id`
    FOREIGN KEY (`id_tipo_identificacion`)
    REFERENCES `controlsales`.`tipo_identificacion` (`id_tipo_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`producto` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT COMMENT 'llave primaria',
  `codigo` VARCHAR(50) NULL,
  `descripcion` VARCHAR(200) NULL,
  `ruta_imagen` VARCHAR(200) NULL,
  `precio1` DECIMAL(12,2) NULL,
  `precio2` DECIMAL(12,2) NULL,
  `precio3` DECIMAL(12,2) NULL,
  `precio4` DECIMAL(12,2) NULL,
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(50) NULL,
  `fecha_actualizacion` DATETIME NULL,
  `usuario_actualizacion` VARCHAR(50) NULL,
  PRIMARY KEY (`id_producto`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`inventario` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`inventario` (
  `id_inventario` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NULL,
  `existencia` INT NULL,
  `costo_unitario` DECIMAL(12,2) NULL,
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(50) NULL,
  `fecha_actualizacion` DATETIME NULL,
  `usuario_actualizacion` VARCHAR(50) NULL,
  PRIMARY KEY (`id_inventario`),
  INDEX `fk_inventario_producto_idx` (`id_producto` ASC),
  CONSTRAINT `fk_inventario_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `controlsales`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`tienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`tienda` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`tienda` (
  `id_tienda` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(200) NULL,
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(50) NULL,
  PRIMARY KEY (`id_tienda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`compra` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`compra` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `id_proveedor` INT NULL,
  `id_producto` INT NULL,
  `id_tienda` INT NULL,
  `cantidad` INT NULL,
  `costo_unitario` DECIMAL(12,2) NULL,
  `costo_total` DECIMAL(12,2) NULL,
  `fecha_compra` DATETIME NULL,
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(50) NULL,
  `fecha_actualizacion` DATETIME NULL,
  `usuario_actualizacion` VARCHAR(50) NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `fk_compra_proveedor_idx` (`id_proveedor` ASC),
  INDEX `fk_compra_producto_idx` (`id_producto` ASC),
  INDEX `fk_compra_tienda_idx` (`id_tienda` ASC),
  CONSTRAINT `fk_compra_proveedor`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `controlsales`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `controlsales`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_tienda`
    FOREIGN KEY (`id_tienda`)
    REFERENCES `controlsales`.`tienda` (`id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`inventario_tienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`inventario_tienda` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`inventario_tienda` (
  `id_inventario_tienda` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NULL,
  `id_tienda` INT NULL,
  `existencia` INT NULL,
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(50) NULL,
  `fecha_actualizacion` DATETIME NULL,
  `usuario_actualizacion` VARCHAR(50) NULL,
  PRIMARY KEY (`id_inventario_tienda`),
  INDEX `fk_inventario_tienda_t_idx` (`id_tienda` ASC),
  INDEX `fk_inventario_producto_t_idx` (`id_producto` ASC),
  CONSTRAINT `fk_inventario_tienda_t`
    FOREIGN KEY (`id_tienda`)
    REFERENCES `controlsales`.`tienda` (`id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_producto_t`
    FOREIGN KEY (`id_producto`)
    REFERENCES `controlsales`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`impuesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`impuesto` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`impuesto` (
  `id_impuesto` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  `valor` INT NULL,
  `sigla` VARCHAR(10) NULL,
  PRIMARY KEY (`id_impuesto`),
  UNIQUE INDEX `sigla_UNIQUE` (`sigla` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`factura` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`factura` (
  `id_factura` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NULL,
  `vendedor` VARCHAR(200) NULL,
  `numero_factura` VARCHAR(45) NULL,
  `fecha_venta` DATETIME NULL,
  `fecha_vencimiento` DATETIME NULL,
  `tipo_pago` VARCHAR(50) NULL,
  `subtotal` DECIMAL(12,2) NULL,
  `iva` DECIMAL(12,2) NULL,
  `total` DECIMAL(12,2) NULL,
  `efectivo` DECIMAL(12,2) NULL,
  `cambio` DECIMAL(12,2) NULL,
  `id_tienda` INT NULL,
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(50) NULL,
  PRIMARY KEY (`id_factura`),
  INDEX `fk_factura_cliente_idx` (`id_cliente` ASC),
  INDEX `fk_factura_tienda_idx` (`id_tienda` ASC),
  CONSTRAINT `fk_factura_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `controlsales`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_tienda`
    FOREIGN KEY (`id_tienda`)
    REFERENCES `controlsales`.`tienda` (`id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`factura_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`factura_detalle` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`factura_detalle` (
  `id_factura_detalle` INT NOT NULL AUTO_INCREMENT,
  `id_factura` INT NULL,
  `id_producto` INT NULL,
  `descripcion` VARCHAR(100) NULL,
  `cantidad` INT NULL,
  `precio_unitario` DECIMAL(12,2) NULL,
  `precio_total` DECIMAL(12,2) NULL,
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(50) NULL,
  PRIMARY KEY (`id_factura_detalle`),
  INDEX `fk_factura_detalle_f_idx` (`id_factura` ASC),
  CONSTRAINT `fk_factura_detalle_f`
    FOREIGN KEY (`id_factura`)
    REFERENCES `controlsales`.`factura` (`id_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`usuario` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(200) NULL,
  `apellidos` VARCHAR(200) NULL,
  `id_tipo_identificacion` INT NULL,
  `identificacion` BIGINT(15) NULL,
  `estado` VARCHAR(1) NULL,
  `usuario` VARCHAR(100) NULL,
  `clave` VARCHAR(100) NULL,
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(50) NULL,
  `fecha_actualizacion` DATETIME NULL,
  `usuario_actualizacion` VARCHAR(50) NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_tipo_id_idx` (`id_tipo_identificacion` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  CONSTRAINT `fk_usuario_tipo_id`
    FOREIGN KEY (`id_tipo_identificacion`)
    REFERENCES `controlsales`.`tipo_identificacion` (`id_tipo_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`rol` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `estado` VARCHAR(1) NULL,
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(50) NULL,
  `fecha_actualizacion` DATETIME NULL,
  `usuario_actualizacion` VARCHAR(50) NULL,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`usuario_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`usuario_rol` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`usuario_rol` (
  `id_usuario_rol` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_rol` INT NOT NULL,
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(50) NULL,
  `fecha_actualizacion` DATETIME NULL,
  `usuario_actualizacion` VARCHAR(50) NULL,
  PRIMARY KEY (`id_usuario_rol`),
  INDEX `fk_usuario_rol_usu_idx` (`id_usuario` ASC),
  INDEX `fk_usuario_rol_rol_idx` (`id_rol` ASC),
  UNIQUE INDEX `Unique_usuario_rol` (`id_usuario` ASC, `id_rol` ASC),
  CONSTRAINT `fk_usuario_rol_usu`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `controlsales`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_rol_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `controlsales`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`menu` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`menu` (
  `id_menu` INT NOT NULL AUTO_INCREMENT,
  `id_menu_padre` INT NULL,
  `descripcion` VARCHAR(100) NULL,
  `opcion` VARCHAR(200) NULL,
  `orden` INT NULL,
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(50) NULL,
  PRIMARY KEY (`id_menu`),
  UNIQUE INDEX `opcion_UNIQUE` (`opcion` ASC),
  INDEX `fk_menu_menu_idx` (`id_menu_padre` ASC),
  CONSTRAINT `fk_menu_menu`
    FOREIGN KEY (`id_menu_padre`)
    REFERENCES `controlsales`.`menu` (`id_menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`menu_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`menu_rol` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`menu_rol` (
  `id_menu_rol` INT NOT NULL AUTO_INCREMENT,
  `id_rol` INT NOT NULL,
  `id_menu` INT NOT NULL,
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(50) NULL,
  `fecha_actualizacion` DATETIME NULL,
  `usuario_actualizacion` VARCHAR(50) NULL,
  PRIMARY KEY (`id_menu_rol`),
  INDEX `fk_menu_rol_menu_idx` (`id_menu` ASC),
  UNIQUE INDEX `unique_menu_rol` (`id_rol` ASC, `id_menu` ASC),
  CONSTRAINT `fk_menu_rol_menu`
    FOREIGN KEY (`id_menu`)
    REFERENCES `controlsales`.`menu` (`id_menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_rol_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `controlsales`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`tipo_noveda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`tipo_noveda` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`tipo_noveda` (
  `id_tipo_noveda` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  `sigla` VARCHAR(50) NULL,
  `estado` VARCHAR(1) NULL,
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(50) NULL,
  PRIMARY KEY (`id_tipo_noveda`),
  UNIQUE INDEX `sigla_UNIQUE` (`sigla` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`novedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`novedad` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`novedad` (
  `id_novedad` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NULL,
  `id_tienda` INT NULL,
  `id_tipo_novedad` INT NULL,
  `descripcion` VARCHAR(200) NULL,
  `cantidad` INT NULL,
  `costo_unitario` DECIMAL(12,2) NULL,
  `costo_total` DECIMAL(12,2) NULL,
  `fecha_novedad` DATETIME NULL,
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(50) NULL,
  `fecha_actualizacion` DATETIME NULL,
  `usuario_actualizacion` VARCHAR(50) NULL,
  PRIMARY KEY (`id_novedad`),
  INDEX `fk_novedad_producto_idx` (`id_producto` ASC),
  INDEX `fk_novedad_tienda_idx` (`id_tienda` ASC),
  INDEX `fk_novedad_tipo_nov_idx` (`id_tipo_novedad` ASC),
  CONSTRAINT `fk_novedad_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `controlsales`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_novedad_tienda`
    FOREIGN KEY (`id_tienda`)
    REFERENCES `controlsales`.`tienda` (`id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_novedad_tipo_nov`
    FOREIGN KEY (`id_tipo_novedad`)
    REFERENCES `controlsales`.`tipo_noveda` (`id_tipo_noveda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`pago_proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`pago_proveedor` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`pago_proveedor` (
  `id_pago_proveedor` INT NOT NULL AUTO_INCREMENT,
  `id_proveedor` INT NULL,
  `numero_factura` VARCHAR(50) NULL,
  `valor_total` DECIMAL(12,2) NULL,
  `valor_pagado` DECIMAL(12,2) NULL,
  `fecha_factura` DATETIME NULL,
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(50) NULL,
  `fecha_actualizacion` DATETIME NULL,
  `usuario_actualizacion` VARCHAR(50) NULL,
  PRIMARY KEY (`id_pago_proveedor`),
  UNIQUE INDEX `numero_factura_UNIQUE` (`numero_factura` ASC),
  INDEX `fk_pago_proveedor_idx` (`id_proveedor` ASC),
  CONSTRAINT `fk_pago_proveedor`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `controlsales`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlsales`.`detalle_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlsales`.`detalle_pago` ;

CREATE TABLE IF NOT EXISTS `controlsales`.`detalle_pago` (
  `id_detalle_pago` INT NOT NULL AUTO_INCREMENT,
  `id_pago_proveedor` INT NULL,
  `valor_abono` DECIMAL(12,2) NULL,
  `fecha_abono` DATETIME NULL,
  `fecha_creacion` DATETIME NULL,
  `usuario_creacion` VARCHAR(50) NULL,
  `fecha_actualizacion` DATETIME NULL,
  `usuario_actualizacion` VARCHAR(50) NULL,
  PRIMARY KEY (`id_detalle_pago`),
  INDEX `fk_detalle_pago_proveedor_idx` (`id_pago_proveedor` ASC),
  CONSTRAINT `fk_detalle_pago_proveedor`
    FOREIGN KEY (`id_pago_proveedor`)
    REFERENCES `controlsales`.`pago_proveedor` (`id_pago_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
